### ISSUE TITLE
Add descriptive README.md

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-certificateelement_activity#2]
Add a descriptive README.md 
Provide also a thumbnail for publishing in Moodle's plugins marketplace.

**Comment by elena3ip** [comment]
Subido!

**Comment by jmerinogranizo** [comment]
En el README.md, en el apartado de "Manual Installation" se indica que debe ser instalado en "{your/moodle/dirroot}/admin/tool/certificate/activity" cuando debería ser "{your/moodle/dirroot}/admin/tool/certificate/element/"

**Comment by elena3ip** [comment]
Corregido!
