### ISSUE TITLE
Error en la validación en certificados de modelos asociados a una plantilla que contienen certificateelement_activity

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/moodle-certificateelement_activity#4]
1. He creado una plantilla en la que he añadido un elemento de tipo "Activity". En concreto de tipo Activity name.
2. He creado un modelo asociado a esa plantilla y lo he asociado a un contexto de categoría. Ese modelo es de tipo único, con diferentes idiomas, con validación "None" y con almacenamiento "local".
3. Como profesor he creado una actividad "certificado de alumno" asociado a ese modelo.
4. El profesor al emitir un certificado le da el siguiente error.

![image](https://github.com/user-attachments/assets/1d4d0fa6-dabe-4103-96c7-ae82d93a4639)

Aunque todo está bien configurado (modelid, certifygenid, templateid) en las tablas certifygen, certifygen_validations, certifygen_cmodels, certifygen_model.
Saludos.

**Comment by elena3ip** [comment]
Solucionado! al cambiar la table mdl_certifygen no revisé que le afectaba a este elemento.
